version: '2'
services:
    dcmt-app:
        image: dcmt
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://dcmt-mysql:3306/dcmt?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    dcmt-mysql:
        extends:
            file: mysql.yml
            service: dcmt-mysql
